### ISSUE TITLE
TypeError: Cannot read properties of null // YouTube Channels

### ISSUE THREAD

**Issue by jelliott-git** [RicSti/google-ads-script-youtube-channel-excluder#3]
Hallo RicSti,
ich habe deinen Code kopiert, ein Google Sheet erstellt ("Beispielwert" in Spalte 1 / Zeile 1) und entsprechenden Platzhalter im Code ersetzt. Im selben Google Account, den ich für Google Ads nutze, habe ich in der Google Cloud die drei YouTube APIs aktiviert. Ich bin da leider Anfänger, aber für mich sieht diese Fehlermeldung bei Ausführung des Codes so aus, als würde da die Verbindung zur API fehlen. YouTube ist aber verknüpft. Ich weiß nicht, was ich noch verknüpfen muss.

```
TypeError: Cannot read properties of null (reading 'getLastRow')
    at getAllowedYouTubeChannels (Code:126:23)
    at checkYouTubeChannels (Code:58:37)
    at main (Code:42:41)
    at Object.<anonymous> (adsapp_compiled:20662:54)
```

**Comment by RicSti** [comment]
Hi @jelliott-git , der Fehler hängt eher mit dem Sheet zusammen. Vermutlich hast Du in der ersten Zeile keinen Beispielwert eingetragen. (Siehe Anleitung bei "[...] Das hinterlegte Google Sheet benötigt nur eine Spalte mit einem Beispielwert in der ersten Zeile. [...])

Das lässt sich im Skript sicherlich mit einer weiteren Schleife schöner lösen. Den Schönheitsfehler bitte ich deshalb zu verzeihen.

Gib dann gern nochmal Bescheid, ob damit Dein Problem behoben werden konnte.

**Comment by jelliott-git** [comment]
Hallo RicSti, danke für deine Antwort!

Wie hat denn der Beispielwert auszusehen? Und so wie ich das verstehe, gehts ja erstmal nur um das erste Feld also 1. Spalte, 1. Zeile.

![image](https://github.com/RicSti/google-ads-script-youtube-channel-excluder/assets/60464494/fec07312-0786-421d-92f6-65d7361a3fd4)

**Comment by RicSti** [comment]
Hi @jelliott-git , Vielen Dank für Deine Geduld! In der ersten Zeile kann theoretisch jeder x-beliebige Wert stehen. Eine sprechende Spaltenübrschrift wie z.B. "whitelisted" würde aber durchaus Sinn machen. :)

**Comment by jelliott-git** [comment]
Hi @RicSti ,
ich hab das Google Sheet regelrecht mit Text gepflastert, aber die Fehlermeldung ändert sich nicht. X(
Könnte es an etwas anderem liegen? Ein Kollege und ich haben uns zuvor gefragt, wie das Script mit den 3 YT-APIs arbeitet zwecks Token / Auth o.ä.
![Screenshot 2024-03-20 134437](https://github.com/RicSti/google-ads-script-youtube-channel-excluder/assets/60464494/03829157-450b-4c7b-a1f9-086c6a155daf)

**Comment by RicSti** [comment]
Hi @jelliott-git , Ihr braucht keine Tokens und auch keine drei APIs. Ich habe den Installationsvorgang gerade auch nochmal erfolgreich getestet. Sicherheitshalber habe ich auch noch eine Tabellenvorlage erstellt.

Könntest Du bitte nochmal die Punkte einzeln wie folgt durchgehen?

1. Kopiere den Script-Code in ein neues Google Ads Skript
2. Aktivierte im Skript unter "Erweiterte APIs" (rechts oben) die API "YouTube" ("YouTube Analytics" wird nicht benötigt
3. Kopiere die Tabellenvorlage von hier: https://docs.google.com/spreadsheets/d/1kARzLXRa-HwiTOQDdWgFRr7_4XdUaXN4TolEoocRhKM/copy
4. Trage in Zeile 20 des Skripts die URL Deiner(!) Tabellenkopie ein.
5. Trage in Zeile 21 des Skripts den Namen des Tabellenblatts ein, in diesem Fall "whitelist"
6. Trage in Zeile 22 die Empfänger E-Mail-Adresse(n) ein
7. Autorisiere das Skript und speichere es (dieser Vorgang kann zweimal nötig sein - Du erhältst ggf. eine entsprechende Meldung am oberen Bildschirmrand. Dann bitte einfach Skript schließen, neu öffnen und die fehlende Autorisierung nachholen)
8. Lasse die Vorschau durchlaufen. (ggf. ist beim ersten Aufruf nochmal eine separate Autorisierung für den Mail-Versand nötig)

Danach solltest Du zumindest eine leere E-Mail erhalten, was beutet, dass der Excluder zwar durchgelaufen ist, aber nichts zu tun hatte.

Ich hoffe, das klappt jetzt so bei Dir.

**Comment by jelliott-git** [comment]
Hi @RicSti !
Danke für deine Mühe und die Schritt für Schritt-Anleitung + Beispiel-Sheet! 

Was ich jetzt feststellen konnte war, 
1. dass es die Fehlermeldung _"Exception: Invalid argument: url"_ gab, wenn man die Sheet-URL ohne "/" am Ende platziert hatte. 
2. dass man den Namen des "Tabellenblattes" nehmen musste und nicht den Namen des Sheets. Evtl. hat das auch schon den Fehler behoben.

Ansonsten wurde nun eine Mail verschickt und das Script ist anstandslos durchgelaufen. 
Bei meiner Testkampagne gab es jetzt tatsächlich 0 Exclusions (die eigentliche Kampagne, um die es ging, war inzwischen ausgelaufen.) 
Sollte sich nicht trotzdem das Sheet in irgendeiner Form ändern? 
Eventuell kann ich das Script am Montag nochmal anderswo testen.

**Comment by RicSti** [comment]
Hi @jelliott-git! Sehr gerne. Und vielen Dank für die Rückmeldung! Freut mich, dass es jetzt bei Dir klappt.
Das Sheet bleibt unverändert, solange keine Kanäle in der Whitelist ergänzt werden.
